export const IMAGE_MANAGER = {BACKGROUND: 'background', NYAN: 'nyan', BALL: 'ball', OCTOCAT: 'octocat'}

export const IMAGES = [IMAGE_MANAGER.BACKGROUND, IMAGE_MANAGER.NYAN, IMAGE_MANAGER.BALL, IMAGE_MANAGER.OCTOCAT]
